spring:
  datasource:
    url: jdbc:sqlserver://10.53.8.10:1433;databaseName=JC_DEV;encrypt=true;trustServerCertificate=true
    username: emf_user
    password: Emes1234!@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # ✅ 테이블명 그대로 사용
    properties:
      hibernate:
      # dialect는 없어도 자동으로 SQLServerDialect 잡아주니까, 경고 없애려면 지워도 됨
      # dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    open-in-view: false

# 스마트공장 로그 API 설정
smart-factory:
  log:
    url: https://log.smart-factory.kr/apisvc/sendLogData.json
    crtfc-key: $5$API$oiQqQjAcFNXt0BevZ1mWhoJXEVuCwfps1caur/EUdc2

# Swagger(springdoc-openapi) 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

logging:
  level:
    root: INFO # 전체 로그 기본 INFO
    com.jc.log_api: DEBUG # 프로젝트 패키지 DEBUG
    org.springframework.web.client.RestTemplate: DEBUG #전송 로그를 실제로 보기 위한 추가
    org.springframework.http.client: DEBUG #전송 로그를 실제로 보기 위한 추가
    org.springframework.web: INFO # 스프링 Web은 INFO
    org.hibernate.SQL: DEBUG # 실행되는 SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
